#target name
target_name = 'filter_stage_unit_test'

#implicit dependencies
config_file = ['../../config/sdr_config.xml','stimulus.xml']
#source files
source_files = 'test_bench.cpp'

#custom build flags
flags = ['-std=gnu++0x', '-Wall', '-W', '-DTIXML_USE_TICPP']

#setup libraries to link and paths
libs=['tinyxmlcpp', 'systemc']
lib_path=['/usr/lib','/usr/local/lib']

#define build environment
env = Environment(LIBS=libs, LIBPATH=lib_path, CXXFLAGS=flags, 
      CPPPATH=['/usr/local/include/sdr_simulator','./'] )

code_gen = env.Program( target='code_generator', source='generate_header.cpp')
env.Depends( code_gen, config_file)

generate_header = env.Command('Cic.hpp', code_gen, './code_generator')
env.Depends( generate_header, config_file )

prog1 = env.Program( target=target_name , source=source_files )
env.Depends( prog1, generate_header )

env.Clean('.', env.Glob('*.dat'))

