
def options(opt):
   opt.load('compiler_c compiler_cxx')

def configure(cnf):
   cnf.load('compiler_c compiler_cxx')
   cnf.check(
      features     = 'cxx cxxprogram',
      libpath      = ['/usr/lib/','/usr/local/lib'],
      cflags       = ['-std=gnu++0x','-Wall','-W','-02'],
      )

def build(bld):

   # copy over sdr configuration file
   bld.exec_command('cp stimulus.yml build/stimulus.yml')

   ## build primary program
   bld.add_group(
   bld(
      name     = 'test_bench',
      features = 'cxx cxxprogram',
      includes = ['.'],
      source   = 'test_bench.cpp',
      target   = 'cic_test',
      lib      = ['yaml-cpp','systemc'],
      )
   )
