import os
import sys
import shutil

def options(ctx):
        ctx.load('compiler_c compiler_cxx')

def configure(ctx):
        ctx.load('compiler_c compiler_cxx')
        ctx.check(
                  features     = 'cxx cxxprogram',
                  libpath      = ['/usr/lib/','/usr/local/lib'],
                  lib          = ['yaml-cpp'],
                  cflags       = ['-std=gnu++0x','-Wall','-W','-02'],
                  uselib_store = 'M'
                 )

def build(ctx):

      ctx(rule='cp ${SRC} ${TGT}', source='src/sdr.yml', target='sdr.yml')

      ## build primary program
      ctx.program(
            name     = 'yaml-test',
            features = 'cxx cxxprogram',
            cxxflags = ['-std=gnu++0x','-Wall', '-W'],
            includes = ['.','src'],
            source   = 'src/yaml-test.cpp',
            target   = 'yaml-test',
            lib      = ['yaml-cpp'],
            )
