import os
import sys
import shutil


def options(ctx):
        ctx.load('compiler_c compiler_cxx')
        ctx.add_option('--gc', action='store_true', default=False,
              help='generate CIC filter')
        ctx.add_option('--tb', action='store_true', default=False,
              help='builds test bench')

def configure(ctx):
        ctx.load('compiler_c compiler_cxx')
        ctx.check(
                  features     = 'cxx cxxprogram',
                  libpath      = ['/usr/lib/','/usr/local/lib'],
                  libs         = ['yaml-cpp'],
                  cflags       = ['-std=gnu++0x','-Wall','-02'],
                 )

        ## define config file location
        ctx.env.CONFIG_FILE = ctx.path.abspath() + os.sep + 'config' + os.sep + 'sdr.yml'

def build(bld):

   # copy over sdr configuration file
   bld.exec_command('cp sdr.yml build/sdr.yml')

   # copy over the hard-coded configuration file
   bld.exec_command('cp configuration.hpp build/configuration.hpp')

   # copy over sdr configuration file
   bld.exec_command('cp stimulus.yml build/stimulus.yml')

   # copy over shared library
   bld(rule='cp ${SRC} ${TGT}', source='../../build/libsdr-yaml.so', target='libsdr-yaml.so'),

   #bld(rule='cp ${SRC} ${TGT}', source='src/sdr.yml', target='sdr.yml')

   if bld.options.gc:

      print('GENERATING CIC FILTER ...')

      ## build code generator
      bld.add_group(
        bld(
           name     = 'cic_generator',
           features = 'cxx cxxprogram',
           cxxflags = ['-std=gnu++0x','-Wall', '-W'],
           includes = '/usr/local/include',
           source   = 'generate_cic.cpp',
           target   = 'cic_generator',
           lib      = ['yaml-cpp','sdr-yaml'],
           libpath  = ['.']
           )
      )

      # generate code
      bld.add_group(
         bld(
            name     = 'generate_cic',
            rule     = bld.path.abspath() + '/build/cic_generator ${CONFIG_FILE}',
            source   = ['cic_generator'],
         )
      )


   ## build primary program
   bld.add_group(
      bld(
         name     = 'test_bench',
         features = 'cxx cxxprogram',
         cxxflags = ['-std=gnu++0x', '-Wall', '-W'],
         includes = ['.'],
         source   = 'test_bench.cpp',
         target   = 'test_rx_channel',
         lib      = ['yaml-cpp','systemc'],
         )
      )

