#target name
target_name = 'cic_error_analysis_test'

source_files = 'test_bench.cpp'

#custom build flags
flags = ['-Wall', '-W']

#define build environment
env = Environment(CXXFLAGS=flags)

prog1 = env.Program( target=target_name , source=source_files )
