#!/usr/bin/env python
import os
import sys
import shutil

if not os.geteuid()==0:
   sys.exit('\nERROR: Root Acces is required to execute this script.\n')

src_dir = '../include'
dst_dir = '/usr/local/include/sdr_simulator'

try:
   shutil.rmtree(dst_dir)
except Exception as ex:
   print(ex)

try:
   print('Creating Directory Tree...')
   shutil.copytree(src_dir,dst_dir,symlinks=True)
   print('Header installation complete.')
except Exception as ex:
   print(ex)
