import os
import sys
import shutil


def options(ctx):
        ctx.load('compiler_c compiler_cxx')
        ctx.add_option('--gc', action='store_true', default=False,
              help='generate CIC filter')
        ctx.add_option('--tb', action='store_true', default=False,
              help='builds test bench')

def configure(ctx):
        ctx.load('compiler_c compiler_cxx')
        ctx.check(
                  features     = 'cxx cxxprogram',
                  libpath      = ['/usr/lib/','/usr/local/lib'],
                  lib          = ['tinyxmlcpp'],
                  cflags       = ['-std=gnu++0x','-Wall','-02'],
                  defines      = ['TIXML_USE_TICPP'],
                  uselib_store = 'M'
                 )

        ## define config file location
        ctx.env.CONFIG_FILE = ctx.path.abspath() + os.sep + 'config' + os.sep + 'sdr_config.xml'

def build(ctx):

   if ctx.options.gc:

      print('GENERATING CIC FILTER ...')

      ## build code generator
      ctx.add_group(
        ctx(
           name     = 'code_generator',
           features = 'cxx cxxprogram',
           cxxflags = ['-std=gnu++0x','-Wall', '-W', '-DTIXML_USE_TICPP'],
           includes = '/usr/local/include',
           source   = 'src/generate_header.cpp',
           target   = 'code_generator',
           defines  = ['TIXML_USE_TICPP'],
           lib      = ['tinyxmlcpp'],
           )
      )

      ### generate code
      ctx.add_group(
         ctx(
         name     = 'generate_header',
         rule     = ctx.path.abspath() + os.sep + 'build' + os.sep + 'code_generator ${CONFIG_FILE}',
         source   = ['code_generator'],
         )
      )

   ## build primary program
   ctx.add_group(
      ctx(
         name     = 'test_bench',
         features = 'cxx cxxprogram',
         cxxflags = ['-std=gnu++0x', '-Wall', '-W', '-DTIXML_USE_TICPP'],
         includes = ['.','src'],
         source   = 'src/test_bench.cpp',
         target   = 'test_rx_channel',
         defines  = ['TIXML_USE_TICPP'],
         lib      = ['tinyxmlcpp','systemc'],
         )
      )

