#target name
target_name = 'accumulator_unit_test'

#source files
source_files = 'test_bench.cpp'

#custom build flags
flags = ['-Wall', '-W', '-DTIXML_USE_TICPP']

#setup libraries to link and paths
libs=['tinyxmlcpp', 'systemc']
lib_path=['/usr/lib','/usr/local/lib']

#define build environment
env = Environment(LIBS=libs, LIBPATH=lib_path, CXXFLAGS=flags)

code_gen = env.Program( target='code_generator', source='generate_header.cpp')

generate_header = env.Command('test_bench.hpp', code_gen, './code_generator')
prog1 = env.Program( target=target_name , source=source_files )
env.Depends( prog1, generate_header )

env.Clean('.', ['accumulator_output.dat','accumulator_trunc_output.dat'])

# code generator
#g++ -o codeGen generate_header.cpp -DTIXML_USE_TICPP -ltinyxmlcpp
